---

- name: Extract the zipped artifact
  unarchive: 
    src:  ~/project/artifact.tar.gz
    dest: ~/

- name: Install dependencies
  become: true
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: Install pm2
  become: true
  npm: 
    name: pm2
    global: yes

- name: start pm2
  command: 
    cmd: pm2 start npm -- start